"""
Base strategy class for sentiment-based trading strategies.

All trading strategies inherit from this base class.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Optional

from src.data.models import OrderSide, StockQuote
from src.sentiment.aggregator import SentimentSignal


class StrategyType(str, Enum):
    """Types of trading strategies."""

    MOMENTUM = "momentum"  # Follow sentiment direction
    MEAN_REVERSION = "mean_reversion"  # Fade extreme sentiment
    NEWS_EVENT = "news_event"  # React to significant news
    COMBINED = "combined"  # Multi-strategy approach


class SignalAction(str, Enum):
    """Trading signal actions."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE_LONG = "close_long"
    CLOSE_SHORT = "close_short"


@dataclass
class StrategySignal:
    """Signal generated by a trading strategy."""

    symbol: str
    action: SignalAction
    confidence: float  # 0-1, how confident the strategy is
    reason: str  # Human-readable explanation
    timestamp: datetime
    strategy_type: StrategyType

    # Optional position sizing hints
    suggested_size_percent: Optional[float] = None  # % of portfolio
    stop_loss_percent: Optional[float] = None
    take_profit_percent: Optional[float] = None

    # Underlying sentiment data
    sentiment_score: Optional[float] = None
    sentiment_trend: Optional[str] = None


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    Strategies analyze sentiment signals and market data to generate
    trading signals.
    """

    def __init__(
        self,
        name: str,
        strategy_type: StrategyType,
        min_confidence: float = 0.4,
    ):
        """
        Initialize base strategy.

        Args:
            name: Strategy name
            strategy_type: Type of strategy
            min_confidence: Minimum confidence threshold for signals
        """
        self.name = name
        self.strategy_type = strategy_type
        self.min_confidence = min_confidence
        self._enabled = True
        self._last_signals: dict[str, StrategySignal] = {}

    @property
    def enabled(self) -> bool:
        """Check if strategy is enabled."""
        return self._enabled

    def enable(self):
        """Enable the strategy."""
        self._enabled = True

    def disable(self):
        """Disable the strategy."""
        self._enabled = False

    @abstractmethod
    def analyze(
        self,
        symbol: str,
        sentiment: SentimentSignal,
        quote: Optional[StockQuote] = None,
        current_position: Optional[float] = None,
    ) -> Optional[StrategySignal]:
        """
        Analyze sentiment and market data to generate a trading signal.

        Args:
            symbol: Stock symbol
            sentiment: Current sentiment signal
            quote: Optional current price quote
            current_position: Optional current position size (+ for long, - for short)

        Returns:
            StrategySignal or None if no action recommended
        """
        pass

    def should_enter_long(
        self,
        sentiment: SentimentSignal,
        current_position: Optional[float] = None,
    ) -> bool:
        """Check if conditions favor entering a long position."""
        # Don't enter if already long
        if current_position and current_position > 0:
            return False
        return sentiment.is_actionable and sentiment.sentiment_score > 0

    def should_enter_short(
        self,
        sentiment: SentimentSignal,
        current_position: Optional[float] = None,
    ) -> bool:
        """Check if conditions favor entering a short position."""
        # Don't enter if already short
        if current_position and current_position < 0:
            return False
        return sentiment.is_actionable and sentiment.sentiment_score < 0

    def should_exit_long(
        self,
        sentiment: SentimentSignal,
        current_position: Optional[float] = None,
    ) -> bool:
        """Check if conditions favor exiting a long position."""
        if not current_position or current_position <= 0:
            return False
        # Exit long if sentiment turns negative
        return sentiment.sentiment_score < -0.1 or sentiment.trend == "deteriorating"

    def should_exit_short(
        self,
        sentiment: SentimentSignal,
        current_position: Optional[float] = None,
    ) -> bool:
        """Check if conditions favor exiting a short position."""
        if not current_position or current_position >= 0:
            return False
        # Exit short if sentiment turns positive
        return sentiment.sentiment_score > 0.1 or sentiment.trend == "improving"

    def get_last_signal(self, symbol: str) -> Optional[StrategySignal]:
        """Get the last signal generated for a symbol."""
        return self._last_signals.get(symbol)

    def _cache_signal(self, signal: StrategySignal):
        """Cache a generated signal."""
        self._last_signals[signal.symbol] = signal

    def clear_cache(self, symbol: Optional[str] = None):
        """Clear cached signals."""
        if symbol:
            self._last_signals.pop(symbol, None)
        else:
            self._last_signals.clear()
